download_url_bvFTD: xxx
download_url_HC: yyy

raw_dir_bvFTD: /data/raw/bvFTD/bvFTD_T1/
raw_dir_HC: /data/raw/bvFTD/HC_T1/

bvFTD_processed_dir: /data/processed//bvFTD/bvFTD_T1
HC_processed_dir: /data/processed/bvFTD/HC_T1